[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-static",
    "-C", "link-arg=--export-dynamic",
    "-C", "link-arg=/home/mathew/Developer/totebox-os/build/crt0.o",
    "-C", "link-arg=-z", "-C", "link-arg=max-page-size=4096",
    "-C", "link-arg=-n",
    "-C", "link-arg=-u", "-C", "link-arg=__sel4_ipc_buffer_obj",
    "-C", "link-arg=-u", "-C", "link-arg=microkit_name",
]
